---
name: Aptly Importer

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-18.04
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install aptly repo
        run: |
            sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys ED75B5A4483DA07C
            sudo bash -C "echo 'deb http://repo.aptly.info/ squeeze main' > /etc/apt/source.list.d/aptly.conf"
      - name: Install software
        run: |
            sudo apt-get update
            sudo apt-get install -y gpg python3 aptly
      - name: Setup enviroment
        run: |
            sudo gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keys.gnupg.net --recv-keys 871920D1991BC93C 3B4FE6ACC0B21F32
            sudo gpg --no-default-keyring --keyring trustedkeys.gpg --keyserver keys.gnupg.net --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
      - name: Run tests
        run: |
            python3 scripts/aptly/aptly_importer_TEST.py
